name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git zip libffi-dev python3-dev openjdk-8-jdk

      - name: Install Python dependencies
        run: |
          pip install cython buildozer

      - name: Setup Android SDK
        run: |
          ANDROID_HOME=$HOME/android-sdk
          mkdir -p $ANDROID_HOME
          mkdir -p $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip -O android-cmdline-tools.zip
          unzip android-cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Update Android SDK Manager and install Build-Tools
        run: |
          sdkmanager --update
          echo "y" | sdkmanager "build-tools;34.0.0" "platform-tools" "platforms;android-34"
          echo "y" | sdkmanager --licenses

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-file
          path: bin/*.apk
